// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PaymentSimplifier.Infrastructure;

#nullable disable

namespace PaymentSimplifier.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260808005717_add-table-transaction")]
    partial class addtabletransaction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PaymentSimplifier.Domain.Transactions.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PayeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("payee_id");

                    b.Property<Guid>("PayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("payer_id");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.HasIndex("PayeeId")
                        .HasDatabaseName("ix_transactions_payee_id");

                    b.HasIndex("PayerId")
                        .HasDatabaseName("ix_transactions_payer_id");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("PaymentSimplifier.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("balance");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password");

                    b.Property<int>("UserType")
                        .HasColumnType("integer")
                        .HasColumnName("user_type");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("019fd90d-e427-74cd-aaf7-a6464f779375"),
                            Balance = 0m,
                            Cpf = "12345678",
                            Email = "lojista@gmail.com",
                            Name = "Lojista1",
                            Password = "lojista1",
                            UserType = 2
                        },
                        new
                        {
                            Id = new Guid("019fd90d-97c1-720c-812b-f502f65f600d"),
                            Balance = 0m,
                            Cpf = "12345679",
                            Email = "user@gmail.com",
                            Name = "User1",
                            Password = "user1",
                            UserType = 1
                        });
                });

            modelBuilder.Entity("PaymentSimplifier.Domain.Transactions.Transaction", b =>
                {
                    b.HasOne("PaymentSimplifier.Domain.Users.User", "Payee")
                        .WithMany("TransactionsForPayee")
                        .HasForeignKey("PayeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_users_payee_id");

                    b.HasOne("PaymentSimplifier.Domain.Users.User", "Payer")
                        .WithMany("TransactionsForPayer")
                        .HasForeignKey("PayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_users_payer_id");

                    b.Navigation("Payee");

                    b.Navigation("Payer");
                });

            modelBuilder.Entity("PaymentSimplifier.Domain.Users.User", b =>
                {
                    b.Navigation("TransactionsForPayee");

                    b.Navigation("TransactionsForPayer");
                });
#pragma warning restore 612, 618
        }
    }
}
